version: 2

builds:
  - main: ./cmd/tmd
    binary: tmd
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64

archives:
  - formats:
      - tar.gz
    name_template: "tmd-{{ .Os }}-{{ if eq .Arch \"amd64\" }}x64{{ else }}{{ .Arch }}{{ end }}"
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: "SHA256SUMS.txt"
  algorithm: sha256

changelog:
  sort: asc

release:
  github:
    owner: typemd
    name: typemd
