name: Deploy site to GitHub Pages repo

on:
  push:
    branches: [main]
    paths:
      - "websites/site/**"
  workflow_dispatch:

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Configure SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SITE_DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan github.com >> ~/.ssh/known_hosts
      - name: Push site subtree
        run: git push "git@github.com:typemd/typemd.io.git" $(git subtree split --prefix=websites/site):refs/heads/main --force
