name: Deploy subtree to GitHub Pages repos

on:
  push:
    branches: [main]
    paths:
      - "site/**"
      - "docs/**"

jobs:
  deploy-site:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push site subtree
        run: git push "https://x-access-token:${DEPLOY_TOKEN}@github.com/typemd/typemd.io.git" $(git subtree split --prefix=site):refs/heads/main --force
        env:
          DEPLOY_TOKEN: ${{ secrets.SUBTREE_DEPLOY_TOKEN }}

  deploy-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Push docs subtree
        run: git push "https://x-access-token:${DEPLOY_TOKEN}@github.com/typemd/docs.git" $(git subtree split --prefix=docs):refs/heads/main --force
        env:
          DEPLOY_TOKEN: ${{ secrets.SUBTREE_DEPLOY_TOKEN }}
